replace_words = {
    word.lower(): "{}_value".format(word.lower())
    for word in [
        "and",
        "except",
        "lambda",
        "with",
        "as",
        "finally",
        "nonlocal",
        "while",
        "assert",
        "false",
        "None",
        "yield",
        "break",
        "for",
        "not",
        "class",
        "from",
        "or",
        "continue",
        "global",
        "pass",
        "def",
        "if",
        "raise",
        "del",
        "import",
        "return",
        "elif",
        "in",
        "True",
        "else",
        "is",
        "try",
    ]
}
